name: generator-prod

services:

  generator-prod-api:
    image: ${FLASK_BLUEPRINT_IMAGE}
    build:
      context: .
      dockerfile: 'Dockerfile.prod'
    container_name: generator-prod-api
    restart: always
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:${DB_ROOT_PASSWORD}@generator-prod-db:3306/generator-prod
      - RIOT_API_KEY=${RIOT_API_KEY}
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - 80:5000
    depends_on:
      generator-prod-db:
        condition: service_healthy

  generator-prod-db:
    image: mysql:8.4.4
    container_name: generator-prod-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: generator-prod
    healthcheck:
      test: mysqladmin ping -h localhost -uroot --password=$$MYSQL_ROOT_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - 3306:3306
    volumes:
      - generator-prod-db:/var/lib/mysql

volumes:
  generator-prod-db: